### ISSUE TITLE
NoSuchMethodError : com.google.common.base.Preconditions.checkArgument

### ISSUE THREAD

**Issue by craph** [google/closure-templates#128] opened 2017-03-10 10:57 UTC
I have updated my soy maven dependency from 2016-08-25 to 2017-02-01

and now when I am trying to : 
`soyFileSet.compileToJsSrc(...,...)`

> java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
	at com.google.template.soy.soytree.RawTextNode$SourceOffsets$Builder.add(RawTextNode.java:416)
	at com.google.template.soy.soyparse.RawTextBuilder.append(RawTextBuilder.java:180)
	at com.google.template.soy.soyparse.RawTextBuilder.addBasic(RawTextBuilder.java:101)
	at com.google.template.soy.soyparse.SoyFileParser.TemplateHeader(SoyFileParser.java:1020)
	at com.google.template.soy.soyparse.SoyFileParser.TemplateHelper(SoyFileParser.java:674)
	at com.google.template.soy.soyparse.SoyFileParser.Template(SoyFileParser.java:620)
	at com.google.template.soy.soyparse.SoyFileParser.SoyFile(SoyFileParser.java:514)
	at com.google.template.soy.soyparse.SoyFileParser.parseSoyFile(SoyFileParser.java:372)
	at com.google.template.soy.SoyFileSetParser.parseSoyFileHelper(SoyFileSetParser.java:169)
	at com.google.template.soy.SoyFileSetParser.parseWithVersions(SoyFileSetParser.java:127)
	at com.google.template.soy.SoyFileSetParser.parse(SoyFileSetParser.java:98)
	at com.google.template.soy.SoyFileSet.parse(SoyFileSet.java:1240)
	at com.google.template.soy.SoyFileSet.compileToJsSrc(SoyFileSet.java:991)

What is the migration process ?

**Comment by craph** [comment] 2017-03-10 12:57
I have two versions of guava : 19.0 and 20.0
I fixed this by including only guava 20.0 but now I have another issue : 

> java.lang.IllegalArgumentException: expected indexes to be added in increasing order
	at com.google.template.soy.soytree.RawTextNode$SourceOffsets$Builder.add(RawTextNode.java:423)
	at com.google.template.soy.soyparse.RawTextBuilder.append(RawTextBuilder.java:180)
	at com.google.template.soy.soyparse.RawTextBuilder.addBasic(RawTextBuilder.java:101)
	at com.google.template.soy.soyparse.SoyFileParser.RawText(SoyFileParser.java:909)
	at com.google.template.soy.soyparse.SoyFileParser.TemplateBlock(SoyFileParser.java:1168)
	at com.google.template.soy.soyparse.SoyFileParser.TemplateHelper(SoyFileParser.java:675)
	at com.google.template.soy.soyparse.SoyFileParser.Template(SoyFileParser.java:620)
	at com.google.template.soy.soyparse.SoyFileParser.SoyFile(SoyFileParser.java:514)
	at com.google.template.soy.soyparse.SoyFileParser.parseSoyFile(SoyFileParser.java:372)
	at com.google.template.soy.SoyFileSetParser.parseSoyFileHelper(SoyFileSetParser.java:169)
	at com.google.template.soy.SoyFileSetParser.parseWithVersions(SoyFileSetParser.java:127)
	at com.google.template.soy.SoyFileSetParser.parse(SoyFileSetParser.java:98)
	at com.google.template.soy.SoyFileSet.parse(SoyFileSet.java:1240)
	at com.google.template.soy.SoyFileSet.parse(SoyFileSet.java:1203)
	at com.google.template.soy.SoyFileSet.compileForServerRendering(SoyFileSet.java:926)
	at com.google.template.soy.SoyFileSet.compileToTofu(SoyFileSet.java:845)

**Comment by lukesandberg** [comment] 2017-03-10 13:19
The second issue is a known bug unfortunately. I should be able to look at
it this week, sorry.

**Comment by craph** [comment] 2017-03-10 13:30
So the best way is to downgrade the version and return to the : 2016-08-25 ?

**Comment by lukesandberg** [comment] 2017-03-10 13:55
For the time being probably. This bug only affects certain templates so you
may be able to find a workaround by finding the template that is triggering
the bug. This would also be some useful data for me :)

**Comment by craph** [comment] 2017-03-10 14:11
This occured when I am trying to render template with ContentKind.JS. that include some other contents from other soy template.

```java
final Renderer renderer = this.getRenderer(fileName, templateName, locale, ptnr, labelDisplay);
if (Arrays.asList(NEED_CONTENTKIND_JS).contains(templateName)) {
	return renderer.setData(data).setContentKind(ContentKind.JS).render();
} else {
	return renderer.setData(data).render();
}
```
The problem occured when I pass in the If case : 
```java
final SoyFileSet soyFileSet = SoyFileSet.builder().add(preparedContent, resource.getName()).add(commonPrepared, common.getName()).build();
if ("soy".equals(type)) {
	tofus.put(tofuKey, new SoyTofuOrJavaScript(soyFileSet.compileToTofu()));
} else if ("js".equals(type)) {
	final SoyJsSrcOptions jsOpt = new SoyJsSrcOptions();
	tofus.put(tofuKey, new SoyTofuOrJavaScript(Joiner.on(';').join(soyFileSet.compileToJsSrc(jsOpt, null))));
}
```

Here is my template for the preparedContent : 
```javascript
{template .onlyConfig kind="js"}
	{@param json: js}
	{let $eca kind="js"}
		{literal}
		window.eca = (function(eca) {
			var data = {/literal}{$json}{literal};
			var merge = function(a, b) {
				for (var key in b) {
					if (typeof b[key] === "object" && typeof a[key] === "object") {
						merge(a[key], b[key]);
					} else {
						a[key] = b[key];
					}
				}
			}

			if (eca.data) {
				merge(eca.data, data);
			} else {
				eca.data = data;
			}
			if (eca.data.HIDE_TOP_NAV) {
				document.body.className = document.body.className + ' hide-nav'
			}
			return eca;
		})(typeof eca === "undefined" ? {} : eca);
		{/literal}
	{/let}
	{literal}(function() { {/literal}
		{$eca}
	{literal}}).call(this);{/literal}
{/template}
```

**Comment by lukesandberg** [comment] 2017-03-10 14:18
Thanks! This helps me narrow down where the bug is. You could try
eliminating the {literal} tags and instead using {lb} and {rb} to print the
curly braces. I suspect the bug occurs when there are multiple literal tags
close to each other.

**Comment by craph** [comment] 2017-03-10 14:20
I will try this and give a feedback to you.

Please, could you tell me where I can find the latest version of soyutils.js ?

**Comment by craph** [comment] 2017-03-10 14:31
So, I have try to remove all content about others template that are used to produce the final soy file with content kind JS and now all is correct.

But the real problem seems to not be in my previous template but in the others.
I will try to make an extract for you of the others template

**Comment by craph** [comment] 2017-03-10 15:43
The issue is seems to be in this template : 
```javascript
{namespace eca.templates.common}

{template .infoMessages}
	{@param infoMessages: ?}
	{if length($infoMessages) > 0}
		<div class="notice overall">
			<h2 class="h3">{msg desc="info.title"}For your information{/msg}</h2>
			<ul>
			{foreach $infoMessage in $infoMessages}
				<li>{$infoMessage}</li>
			{/foreach}
			</ul>
		</div>
	{/if}
{/template}
```
When I remove this template of the eca.templates.common part all is ok.

What is wrong in this template ?

This template is used here (it is the commonPrepared param) : 
```java
final SoyFileSet soyFileSet = SoyFileSet.builder().add(preparedContent, resource.getName()).add(commonPrepared, common.getName()).build();
if ("soy".equals(type)) {
	tofus.put(tofuKey, new SoyTofuOrJavaScript(soyFileSet.compileToTofu()));
} else if ("js".equals(type)) {
	final SoyJsSrcOptions jsOpt = new SoyJsSrcOptions();
	tofus.put(tofuKey, new SoyTofuOrJavaScript(Joiner.on(';').join(soyFileSet.compileToJsSrc(jsOpt, null))));
}
```

**Comment by lukesandberg** [comment] 2017-03-13 17:16
hmmm.  i am unable to reproduce the failure with the HEAD version of soy

i also tried the current version on github with no success.  will keep investigating

**Comment by lukesandberg** [comment] 2017-03-13 19:27
i was able to reproduce a similar failure when using an empty literal `{literal}{/literal}`

i haven't found any other way though.... does that make sense?

**Comment by craph** [comment] 2017-03-13 20:12
The problem occured when I am using this Soy : 
```javascript
{template .onlyConfig kind="js"}
	{@param json: js}
	{let $eca kind="js"}
		{literal}
		window.eca = (function(eca) {
			var data = {/literal}{$json}{literal};
			var merge = function(a, b) {
				for (var key in b) {
					if (typeof b[key] === "object" && typeof a[key] === "object") {
						merge(a[key], b[key]);
					} else {
						a[key] = b[key];
					}
				}
			}

			if (eca.data) {
				merge(eca.data, data);
			} else {
				eca.data = data;
			}
			if (eca.data.HIDE_TOP_NAV) {
				document.body.className = document.body.className + ' hide-nav'
			}
			return eca;
		})(typeof eca === "undefined" ? {} : eca);
		{/literal}
	{/let}
	{literal}(function() { {/literal}
		{$eca}
	{literal}}).call(this);{/literal}
{/template}
```
and on the Java side I am doing this : 
```java
final Resource common = getResource("common");
			final String commonContent = common.getContents();
			final String commonPrepared = templatePreProcessor.execute(commonContent, locale);

			final Resource resource = getResource(name);
			final String content = resource.getContents();
			final String preparedContent = templatePreProcessor.execute(content, locale);
			try {
				final SoyFileSet soyFileSet = SoyFileSet.builder().add(preparedContent, resource.getName()).add(commonPrepared, common.getName()).build();
				if ("soy".equals(type)) {
					tofus.put(tofuKey, new SoyTofuOrJavaScript(soyFileSet.compileToTofu()));
				} else if ("js".equals(type)) {
					final SoyJsSrcOptions jsOpt = new SoyJsSrcOptions();
					tofus.put(tofuKey, new SoyTofuOrJavaScript(Joiner.on(';').join(soyFileSet.compileToJsSrc(jsOpt, null))));
				}
			} catch (Throwable e) {
				e.printStackTrace();
			}
```
in the commonPrepared I have : 
```javascript
{namespace eca.templates.common}

{template .infoMessages}
	{@param infoMessages: ?}
	{if length($infoMessages) > 0}
		<div class="notice overall">
			<h2 class="h3">{msg desc="info.title"}For your information{/msg}</h2>
			<ul>
			{foreach $infoMessage in $infoMessages}
				<li>{$infoMessage}</li>
			{/foreach}
			</ul>
		</div>
	{/if}
{/template}
```
I will try to investigate tomorrow morning about this to give you more example to investigate.
But I think there is an issue somewhere.

**Comment by craph** [comment] 2017-03-23 07:26
@lukesandberg , @mikesamuel ,

Any news about this bloking issue ?

In advance many thanks

**Comment by craph** [comment] 2017-03-27 11:26
@mikesamuel , @lukesandberg ,
Any news ?

**Comment by craph** [comment] 2017-03-31 11:57
@mikesamuel  , @lukesandberg  ,
Any news ?

Thanks.

**Comment by lukesandberg** [comment] 2017-04-04 15:07
this is fixed in the google internal version of closure templates and
should be fixed with the next repo sync

**Comment by craph** [comment] 2017-04-04 18:24
Oh thank you @lukesandberg 
When this will be available a release version in Maven Repo ?

**Closed** 2017-04-12 17:29 UTC

**Comment by craph** [comment] 2017-04-14 14:31
@fenghaolw @lukesandberg  @mikesamuel When this will be available in [MVN repository](http://mvnrepository.com/artifact/com.google.template/soy) ?

Thanks

**Comment by craph** [comment] 2017-04-24 19:13
@fenghaolw @lukesandberg @mikesamuel When this will be available in MVN repository ?

Thanks

**Comment by fenghaolw** [comment] 2017-04-24 21:57
Hi @craph I just released this to maven central.

**Comment by craph** [comment] 2017-05-10 21:32
Hi @fenghaolw Thank you very much.

Just for curiosity, what is the process to release the github project to maven central ?

Many thanks.
